version: '3.8'

services:

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notesdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: notesdb
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
